//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sachin_452_Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int cartId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<int> quantity { get; set; }
        public string productType { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> userid { get; set; }
        public string productName { get; set; }
        public Nullable<int> total { get; set; }
    }
}
