//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sachin_452_Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<int> quantity { get; set; }
        public string productType { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
